export const ItemsData = [
    {
        _id: "657dab0eccc6df20909cfc801",
        itemCode: "sdsad",
        itemName: "Product 1",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 32,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc802",
        itemCode: "sdsad",
        itemName: "Product 2",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 342,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc03",
        itemCode: "sdsad",
        itemName: "Product 3",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 675,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc04",
        itemCode: "sdsad",
        itemName: "Product 4",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 566,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc05",
        itemCode: "sdsad",
        itemName: "Product 5",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 456,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc06",
        itemCode: "sdsad",
        itemName: "Product 6",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 768,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc07",
        itemCode: "sdsad",
        itemName: "Product 7",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 768,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc08",
        itemCode: "sdsad",
        itemName: "Product 8",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 678,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc09",
        itemCode: "sdsad",
        itemName: "Product 9",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 678,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc10",
        itemCode: "sdsad",
        itemName: "Product 10 ",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 567,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
    {
        _id: "657dab0eccc6df20909cfc11",
        itemCode: "dfdsfd",
        itemName: "Product 11",
        itemCategory: "sadasd",
        itemSubCategory: "sdsad",
        itemPrice: 567,
        ingredients: "asdasd",
        recipe: "asdasd",
        allergen: "sadsad",
        portionSize: "sadasd",
        status: "asdasd",
        tax: 5,
        discount: 20,
        images: "asdasd",
        currentStock: 100,
        barcode: 21323243,
        salesHistory: "good",
        customNotes: "sadasdas",
        quantity: 1
    },
]